### ISSUE TITLE
Test Errors?

### ISSUE THREAD

**Issue by azev77** [JuliaDiffEq/NeuralNetDiffEq.jl#57]
I ran: https://github.com/JuliaDiffEq/NeuralNetDiffEq.jl/blob/master/test/NNPDENS_tests.jl

For "Black-Scholes-Barenblatt equation"
```Julia
ans = solve(prob, pdealg, verbose=true, maxiters=250, trajectories=m,
alg=EM(), dt=dt, pabstol = 1f-6)
```
It says:
MethodError: no method matching Float32(::Tracker.TrackedReal{Float32})
Closest candidates are:
  Float32(::Real, !Matched::RoundingMode) where T<:AbstractFloat at rounding.jl:200
  Float32(::T) where T<:Number at boot.jl:718
  Float32(!Matched::Int8) at float.jl:60

"Nonlinear Black-Scholes Equation with Default Risk"
```Julia
@time ans = solve(prob, pdealg, verbose=true, maxiters=200, trajectories=m,
                            alg=EM(), dt=dt, pabstol = 1f-6)
```
Says:
MethodError: vcat(::TrackedArray{…,Array{Float32,1}}, ::Array{Tracker.TrackedReal{Float32},1}) is ambiguous. Candidates:

**Comment by ChrisRackauckas** [comment]
I wonder if https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/430 had an effect here. I'll test it sometime tomorrow.

**Comment by ChrisRackauckas** [comment]
See if rolling back that patch fixes it.

**Comment by azev77** [comment]
Sorry @ChrisRackauckas I don't know how to do that

**Comment by ChrisRackauckas** [comment]
`]add DiffEqBase@6.13.1`, and then `]free DiffEqBase` when you're done to return it to normal.

**Comment by azev77** [comment]
Tried, I get a new error in method definition at this line:
```Julia
σ(X,p,t) = Diagonal(sigma*X) #Matrix d x d
```

**Comment by ChrisRackauckas** [comment]
Are you not on Julia 1.3?

**Comment by azev77** [comment]
Yes

**Comment by KirillZubov** [comment]
@azev77 this happens simply because the name `σ` is already defined as `NNlib.σ` in the environment. Just change the name of the function `σ (X, p, t)` to something else, and it should work.
We will fix this soon.

**Comment by azev77** [comment]
Thanks @KirillZubov @ChrisRackauckas 
I'm preparing a blog post on Julia for dynamic economic models. 
I believe currently 
```Julia
ans = solve(prob, pdealg, verbose=true, maxiters=200, trajectories=m,
                            alg=EM(), dt=dt, pabstol = 1f-6)
```
gives u(x=X0, t=tspan[1]). 
How can I recover the entire function: `u(x,t), u_x(x,t)` etc ?

**Comment by ChrisRackauckas** [comment]
>gives u(x=X0, t=tspan[1]).
>How can I recover the entire function: u(x,t), u_x(x,t) etc ?

You are correct that this is what it gives. It's a very specific method for solving the terminal PDE for HJB and stochastic optimal control types of problems, and not one that can compute the full function. There are other methods which can compute the whole function (which are of course slower too) which will be added to the library.

**Comment by azev77** [comment]
Btw, here are other deep BSDE solvers w tf, pytorch :
https://github.com/frankhan91/DeepBSDE?files=1

https://github.com/skyhehe123/DeepBSDE-pytorch?files=1

https://github.com/vduarte/MLEcon

**Comment by ChrisRackauckas** [comment]
Thanks! Is this all cleaned up? I noticed our tests are having some issues right now, but I think @KirillZubov is on it. One of the things we need to fix up is just how long to setup the CI tests for.

**Comment by azev77** [comment]
Btw, I have NeuralNetDiffEq v1.0.1 installed, which is not the latest version. 
For some reason it won't let me install the latest. Not sure if this is relevant.

**Comment by ChrisRackauckas** [comment]
On Julia 1.3 with Flux 0.10?

**Comment by azev77** [comment]
I update my stuff today. 
Julia 1.3.1 
Flux 0.10.1

**Comment by azev77** [comment]
Fyi, when I run the tests now I get a new error at:
```Julia
ans = solve(prob, pdealg, verbose=true, maxiters=200, trajectories=m,
                            alg=EM(), dt=dt, pabstol = 1f-6)
```
UndefVarError: Tracker not defined
getproperty at Base.jl:13 [inlined]

**Comment by ChrisRackauckas** [comment]
Interesting... Tracker doesn't exist in the repo at all.

**Comment by azev77** [comment]
I manually downloaded the latest version w/ 
`] add https://github.com/JuliaDiffEq/NeuralNetDiffEq.jl`
and it works now.

**Comment by ChrisRackauckas** [comment]
All tests are passing on master so tagging.
